### PR TITLE
Cypress empty promise

### LINKED ISSUE #572: Cypress: empty error instability
https://dashboard.cypress.io/projects/ry3x7y/runs/49/test-results/bbeb1f79-a6da-4e33-9f99-b4b23d2383d2/screenshots
(it's not a one-time error, saw it several times already)

Might be as simple as ignoring promises with empty message in https://github.com/equinor/fusion-bmt/blob/master/frontend/cypress/support/mock/external/external.ts, but the follow-up error https://dashboard.cypress.io/projects/ry3x7y/runs/49/test-results/bbeb1f79-a6da-4e33-9f99-b4b23d2383d2 
```
cy.click() failed because it requires a DOM element.

The subject received was:

  > undefined

The previous command that ran was:

  > cy.get()
```
  
  might mean it's not enough

### PR DESCRIPTION
**Pull request by achaikou**
closes #572

### CODE REVIEW

File: frontend/cypress/support/mock/external/external.ts [hunk 1]
```diff
@@ -109,13 +109,22 @@ Cypress.on('uncaught:exception', (err, runnable, promise) => {
...
             /* Log remaining unhandled promises as Cypress sometimes doesn't log them fully */
             console.log('Unhandled promise uncaught: ' + err.message)
         }
     }
 
     /* thrown sometimes when navigating through stepper, looks to be from fusion */
-    if (err.message.includes("Cannot read property 'removeEventListener' of null")) {
+    if (
+        err.message.includes("Cannot read property 'removeEventListener' of null") ||
+        err.message.includes('can\'t access property "removeEventListener", editorRef.current is null')
```
Comment (petterwildhagen) [inline frontend/cypress/support/mock/external/external.ts:126]: I also get Cannot read properties of null (reading 'removeEventListener') --- adding this to different PR
